### ISSUE TITLE
Multiple calls to $firebaseArray/$firebaseObject resolve together

### ISSUE THREAD

**Issue by BetterTrader** [firebase/angularfire#609] opened 2015-04-29 13:22 UTC
Hello,
I'm not sure if it's a bug or a desired behavior (if it is, I'm not sure why), but it seems that if I have multiple calls to, say, $firebaseArray - their $loaded() promise will all resolve together and I'm unable to use the objects until ALL of them returned.

Snippet:
http://codepen.io/anon/pen/aOObqV
In this version, where the big data is not loaded (commented lines 9-10), you can see that the small data resolves quickly.
If you uncomment lines 9-10, you'll be able to see that the small data doesn't resolve until the big data resolves (and then, the small data resolves immediately, which means it was already "ready")
Is this an intentional behavior for $firebaseArray? 
If so - how can I overcome this and get the small data to load quickly while the big data is loading?

**Comment by jwngr** [comment] 2015-04-30 07:02
This looks like an AngularFire bug to me. I'm not sure if there is a workaround at the moment. We will take a look and figure out what the problem is. The fix for you will probably be to wait until we fix this issue and then upgrade to the latest version once we release an update. Thanks for reporting this!

**Comment by jamestalmage** [comment] 2015-04-30 19:14
This is not an AngularFire bug, but a function of how Firebase streams data to the client. The [following code](http://codepen.io/anon/pen/OVVgzY) will produce the exact same results (note that it is not using AngularFire at all):

```js
  ref.child('rows').limitToLast(5000).on('value',function(){
    $scope.bigDataLoaded = 'Big data LOADED';
    $scope.$apply();
  });

  ref.child('rows').limitToLast(1).on('value',function(){
    $scope.smallDataLoaded = 'Small data LOADED';
    $scope.$apply();
  });
```

I am guessing that Firebase starts streaming the response to your `limitToLast(5000)` query first, and it's last row of that result IS the result to your `limitToLast(1)` query. While I am pretty sure Firebase is smart enough to not stream the same data twice, it obviously is not applying any kind of algorithm to get you the smaller payloads quicker, nor is it sending two responses in parallel (by muxing the stream, etc).

> how can I overcome this and get the small data to load quickly while the big data is loading

The trivial answer is simply to request the small data first by moving the small data query up a few lines.  I have tested it and it works as you would expect. If you do not know which dataset is smaller ahead of time, that is going to be tricky.

**Comment by katowulf** [comment] 2015-04-30 19:20
Additionally, it's a bit hard to understand a use case for fetching the same data twice on the same path with two different limit queries. Presumably this is redundant.

**Comment by jamestalmage** [comment] 2015-04-30 19:25
I can see plenty of use cases:
A directive that displays the last 5000 messages, and a `last-updated` or `most-recent-comment` directive. You would never put these two queries in the same controller (as you said - just track the last item of the larger query in that case), but I could see both of them being active at the same time inside your application.

**Comment by katowulf** [comment] 2015-05-01 17:47
Closing this as a non-AngularFire issue.

**Closed by katowulf** 2015-05-01 17:47 UTC
Labels: bug
