### ISSUE TITLE
Auth.$createUserWithEmailAndPassword

### ISSUE THREAD

**Issue by rhsu0268** [firebase/angularfire#820] opened 2016-07-17 21:10 UTC
For some reason after running the Auth.$createUserWithEmailAndPassword, the code inside the the "then" part of the promise isn't running. Was there a problem with this and what is there is a solution? 

Thanks,
Richard

**Comment by jwngr** [comment] 2016-07-18 01:05
Dupe of #782. Just upgrade to the latest `2.0.1` release: https://github.com/firebase/angularfire/releases/tag/v2.0.1.

Also, please use the issue template in the future. It's there for a reason.

**Closed by jwngr** 2016-07-18 01:05 UTC

**Comment by nikmartin** [comment] 2016-07-25 03:21
FYI, I just grabbed the latest 2.0.1 from your link and am still seeing this behavior. Using this code:

```
 $scope.emailPassLogin = function () {
      Auth.$signInWithEmailAndPassword($scope.user.email, $scope.user.password)
        .then(function (response) {
          console.log(response);
        }).catch(function (error) {
        // Handle Errors here.
        $scope.error = error;
        $scope.message = error.message;
      });
    };
```

and calling it with no email or password, I see this in the console:

```
Q {code: "auth/argument-error", message: "createUserWithEmailAndPassword failed: First argument "email" must be a valid string."}
code:"auth/argument-error"
message:"createUserWithEmailAndPassword failed: First argument "email" must be a valid string."
```

But the catch() block is never hit.

**Comment by jwngr** [comment] 2016-07-25 16:27
For better or worse, when possible, the Firebase SDK throws synchronous errors (even in promises) to make debugging easier and to avoid the silent errors symptom common when using promises. That is why the `catch()` block is never called.

The error given here should be pretty self-explanatory. Namely, the first argument must be a string. If you do `console.log($scope.user.email)`, I bet you will see it is either `undefined` or `null`. You should check to make sure your inputs are valid before calling `Auth.$signInWithEmailAndPassword()`.

**Comment by nikmartin** [comment] 2016-07-25 17:03
Yeah, for sure, I'm aware of the error, i was just testing all the boundary cases of account creation and authentication to see what firebase-angular would do with each case, and noticed that this case wasn't returning the error as a promise - agree on the silent error issue, it drives me up a wall in my node.js app.

**Comment by Maxie35** [comment] 2016-11-03 10:37
I'm having the same issue. $scope.user.email does not return undefined or null, it is a valid string. Yet I get the same error. Apparently the issue is not resolved (also I have the latest versions)
