### ISSUE TITLE
$signOut() doesn't immediately sign out the client, and has no way to wait until client is signed out

### ISSUE THREAD

**Issue by joeeames** [firebase/angularfire#832] opened 2016-08-01 18:04 UTC
### Version info

**Angular:**
1.5.8
**Firebase:**
3.2.1
**AngularFire:**
2.0.1

### Test case
http://plnkr.co/edit/3xm2vb5QKX3AH2f9BdE6?p=preview

### Steps to reproduce

click the "anonymous login" button, then click logout on the home page. 

### Expected behavior

The client should be immediately aware that the signOut functionality has been invoked. Either the client should be logged out synchronously, or signOut() should return a promise so that execution can wait until the client has been logged out correctly.

Note that in the logout.js has a commented out call to $timeout for 500ms. If this is code is un commented, then the expected behavior happens, since apparently 500ms is enough for the client to get signed out.

### Actual behavior

When calling $signOut() there is a delay before the user is actually signed out (I'm sure it makes a round trip to the server), so on the clientside, it still thinks the user is signed in, so if after calling $signOut() in the logout.js component you then navigate to a new page with location.path() the new page will use $waitForSignIn which tells the page that the user is authenticated. so the page renders based on the fact that the user is authenticated. But then shortly after that the socket must return, letting the client know that the user is no longer authenticated. But of course no digest is triggered when that happens. Also, since $signOut() is not a promise, you can't wait until the clientside actually knows that the user is signed out. If I add a 500ms delay, then things are fine. $requireSignIn and $waitForSignIn are resolving with valid auth objects instead of null or undefined.

**Comment by jwngr** [comment] 2016-08-01 18:07
Dupe of https://github.com/firebase/angularfire/issues/755. This is fixed with https://github.com/firebase/angularfire/pull/771 but just hasn't been deployed yet.

@katowulf / @davideast - we should cut a new release this week.

**Closed by jwngr** 2016-08-01 18:07 UTC

**Comment by toddmotto** [comment] 2016-08-17 17:09
@jwngr Hey Jacob, when are you expecting the release for AngularFire? Am stuck on this same issue :)

**Comment by joeeames** [comment] 2016-08-17 21:42
ok, if @joeeames is having a problem that's one thing, but if @toddmotto is having an issue, it just got real....

**Comment by jwngr** [comment] 2016-08-17 23:47
Haha I just sent mail to a few people and we are discussing how to get out a new release and what we should include. Apologies on the delay here! We do want to get out a new minor version release which adds first-class support for Firebase Storage, but I think we will cut a release earlier so we can get out a handful of pending changes, including this one. We will aim to cut a release before the end of this week, maybe early next week.

Thanks everyone for their patience!

**Comment by toddmotto** [comment] 2016-08-18 00:40
Haha thanks Joe! And hey no worries, I'm using the firebase global signOut() method that returns a promise at the moment. I'm about to record a full component based app course final project with this setup and it's the only non-angularfire method in there :) thanks so much!

@toddmotto

**Comment by jwngr** [comment] 2016-08-19 21:20
This is fixed in the just-released AngularFire [version 2.0.2](https://github.com/firebase/angularfire/releases/tag/v2.0.2). Sorry for the delay in getting it out!

**Comment by toddmotto** [comment] 2016-08-19 21:59
Ah amazing! I just finished my app today too before recording the screencast, so I can swap out my firebase() global call and am 100% angularfire :D thanks so much. Have a great weekend. 

@toddmotto

**Comment by pilapila** [comment] 2016-12-20 13:50
firebase.auth().signOut().then(function() {
						  
						}, function(error) {
						  
						});
