### ISSUE TITLE
Calling $createUserWithEmailAndPassword while logged in re-logs you in as the new user

### ISSUE THREAD

**Issue by myspivey** [firebase/angularfire#830] opened 2016-07-29 19:46 UTC
### Version info

**Angular:1.4.8
**Firebase:3.2.1
**AngularFire:2.0.1
Latest Chrome

### Test case

https://plnkr.co/edit/acwPMnQJ4lSlOrjxCo0J

### Steps to reproduce

1. Login as a valid user with email and password using $firebaseAuth().$signInWithEmailAndPassword().
2. Call $firebaseAuth().$createUserWithEmailAndPassword()

### Expected behavior

Creates new user without changing current authorization per documentation.

### Actual behavior

Creates user, then updates current logged in user to the newly created user.

**Comment by jwngr** [comment] 2016-07-29 21:59
Thanks for the good report and following the issue template. Which documentation are you referring to? Can you please provide a link? I think this is actually "works as intended" for the `3.x.x` Firebase SDK. It's possible the AngularFire docs are out of date since this is a different behavior than the `2.x.x` SDKs.

**Comment by myspivey** [comment] 2016-07-29 22:32
Ahh yes, interesting. I swear I saw that it said it did not, but checking https://github.com/firebase/angularfire/blob/master/docs/reference.md#createuserwithemailandpasswordemail-password it shows that it does. This is really horrible behavior for trying to create a user management portal. Is there a workaround to this?

**Comment by jwngr** [comment] 2016-07-29 22:40
I'd suggest you give [this Google Groups thread](https://groups.google.com/forum/#!msg/firebase-talk/zYatdVy1QfU/b-qI7iWeAAAJ) a read. Also, please chime in if you don't like the behavior and try to expound on your use case. Closing this issue since to de-dupe the conversation and since AngularFire just calls the method from the underlying Firebase SDK.

**Closed** 2016-07-29 22:40 UTC
Labels: docs, question
