### ISSUE TITLE
bower install angularfire 2

### ISSUE THREAD

**Issue by yuriploc** [firebase/angularfire#733] opened 2016-05-31 16:58 UTC
When I run `$ bower install angularfire#2.0 --save` no angular.min.js file is checked out.
If I run `$ bower install angularfire --save` it installs the 1.2.0 version.

Any ideas of why this is happening?

**Comment by jwngr** [comment] 2016-05-31 17:15
Dupe of #724.

**Closed by jwngr** 2016-05-31 17:15 UTC
Labels: duplicate, question
