### ISSUE TITLE
firebase auth with "Block sites from setting any data" setting.

### ISSUE THREAD

**Issue by leblancmeneses** [firebase/angularfire#814] opened 2016-07-13 14:37 UTC
**Angular:**
v1.5.6

**Firebase:**
Firebase v3.0.3
Build: 3.0.3-rc.1

**AngularFire:**
AngularFire 2.0.1

### Steps to reproduce

This is affected by this setting in chrome browser:
Chrome's Settings > Privacy > Content settings, check "Block sites from setting any data"

auth.$signInWithPopup(type).then(function () {
						.....
					}).catch(function (error) {
						notifyService.error(error, "Authentication failed");
					});

### Expected behavior

AngularFire should either call the catch block or implement a solution that works around this setting.

### Actual behavior

"iframe.js:186 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document."

and 

The angularfire catch block is not called and the user gets no visibility of error and loses trust of the site.

----------------------------

All of my user problems are coming from $signInWithPopup.  Other users have reported blank screens on iphone 6 newest os 
![061e9af1015b9ad673f2fbd1de643721758eecb6f59cf50d67 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/730804/16807136/f2f3ede6-48dc-11e6-80f4-53d5f1da5222.jpg)

app: www.dnwdebt.com

**Comment by jwngr** [comment] 2016-07-15 07:44
Duplicate of https://groups.google.com/forum/#!msg/firebase-angular/nakkHeR320c/iEbq-wW6AAAJ. Since Kato already answered on that thread, let's keep the conversation there.

**Closed by jwngr** 2016-07-15 07:44 UTC
