### ISSUE TITLE
Found an minor error in the Angularfire API Docs.

### ISSUE THREAD

**Issue by AFigueroa** [firebase/angularfire#526] opened 2015-01-11 04:22 UTC
Hello,

In Angularfire's API documentation the $createUser method is asking for an object containing the user's email and password. When given this, the method will break and not register the user. To fix it, I just removed the object and gave the user's email as the first parameter and the user's password as the second, both in the type of string. Once this change was made the $createUser method worked just fine.

Hopes this helps.
Antonio J. Figueroa

**Comment by jwngr** [comment] 2015-01-11 06:38
This is a duplicate of #525.

This is not a documentation error. The API changed with the 0.9.1 release. Just upgrade to that release and your problem will be solved.

**Closed by jwngr** 2015-01-11 06:38 UTC
Labels: duplicate, question
