### ISSUE TITLE
0.9.2 `$asObject().$remove()` throws `permission_denied` after `auth.$removeUser()`

### ISSUE THREAD

**Issue by gigablox** [firebase/angularfire#537] opened 2015-01-24 21:14 UTC
I really appreciate the 0.9.2 fix for the `$remove()` bug on the `$asObject()` as seen before in https://github.com/firebase/angularfire/issues/536. This method now works as expected.

However this still does not fix the `permission_denied` errors I'm finding when using `auth.$removeUser` immediately after the `ref.$asObject().$remove()` success callback.

I have spent a great deal of time putting together a test I hope is useful for you guys to debug against and very clearly illustrates the issue:
http://plnkr.co/edit/aEEj3VX6h7dUmuyMgq5V

I have also made another Firebase with identical security rules.
https://debug001.firebaseio.com/

There is a *signup*, *login*, *logout*, *currentAuth*, *currentUser* helper methods as well as a *refManager* service that should make this easier to debug.

Steps to reproduce:

1. Create an account using the provided form field.
 - email
 - password (with a minimum length of 8 characters)

2. Delete the account using the provided form field.

Using the `console` you should be able to see `permission_denied` errors for these refs right after the `auth.$removeUser` method is invoked in the last `$remove()` success callback.

**Comment by jwngr** [comment] 2015-01-25 19:52
What do your security rules looks like? I assume that is the root cause of your permission denied warnings.

**Comment by gigablox** [comment] 2015-01-25 19:59
@jwngr The data is successfully removed. Nothing is being blocked here - it's just that this error message still appears even after a successfully deletion. Could this still be from my security rules..?

**Comment by jwngr** [comment] 2015-01-27 17:48
Yeah, this is almost certainly due to your security rules. Do your rules rely on the `auth` variable? If so, calling `removeUser()` will clear your logged-in user's state and cause `auth` to be `null`. Maybe that is where things are going wrong, but it's hard to say without knowing more information. Would you mind sharing your security rules? If you don't want to do that here, we can move this discussion to our internal support by emailing support@firebase.com. Just make sure you let them know I sent you so it gets routed back to me or Kato. Also, include the link to this discussion. I will report back here once we track down your issue.

**Comment by jwngr** [comment] 2015-01-30 23:22
Closing this issue as I am pretty sure this is unrelated to AngularFire and is actually due to security rules. If your problem persists, please contact support@firebase.com and we can help you fix your security rules issue.

**Closed by jwngr** 2015-01-30 23:22 UTC
Labels: question
