### ISSUE TITLE
@firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'myID' of undefined

### ISSUE THREAD

**Issue by gate3** [firebase/angularfire#970] opened 2018-05-03 07:56 UTC
### Version info

**Angular:** ^5.2.0 

**Firebase:** ^4.13.1

**AngularFire:** ^5.0.0-rc.6.0

**Other (e.g. Node, browser, operating system) (if applicable):** Firebase Hosting

### Test case

```
getLocations(radius: number, coords: Array<number>) {
        this.geoFire.query({
            center: coords,
            radius: radius
        })
        .on('key_entered', (userKey, location, distance) => {
            
            const existAlready = this.hits.value.filter(h=>h.userKey === userKey)

            if(existAlready.length > 0){
                return
            }

            const u = this.userList.query.ref
                          .child(`/${userKey}`)
                          .on('value',s=>{
                            const {name, address} = s.val()
                            console.log(s.val())
                            let hit = {
                                location,
                                distance,
                                name,
                                address,
                                userKey
                            }
                            
                            let currentHits = this.hits.value
                            currentHits.push(hit)
                            this.hits.next(currentHits)
                            
                            this.eventService.sendMessage(Constants.EVENT_MESSAGES.LOADING, true)

                          })
        })
    }
```

Basically what i am doing is fetching the current location and passing it to the function above 

### Steps to reproduce

I am using angularfire with geofire for a location based app for fetching locations around my user. It works perfectly on my dev machine, but as soon as i build and deploy to firebase hosting, I get a very strange error 

> @firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'myID' of undefined

What i am doing basically is fetching the current location and passing it to the function above, the function is meant to fetch nearby locations and then put them in a behavioursubject. It works well in development like a said, but its a big NO NO on the firebase hosting server.

### Expected behavior
I expect to get back the locations around me saved in firebase.

### Actual behavior
I am getting an error as stated above.

**Comment by faizaaniesta** [comment] 2018-05-08 04:17
I am facing the same problem using the exact setup except for  angularfire2 ^5.0.0-rc.7.

**Comment by 3lywa** [comment] 2018-05-10 14:56
I am having the same issue as well! In dev the code runs fine, onceI switch to `ng build --prod` i get the following message when i run the app `Cannot read property 'myID' of undefined`

**Comment by andre-gois** [comment] 2018-05-11 10:29
same here

**Comment by kotkotoff** [comment] 2018-05-13 17:32
same here

**Comment by toffuser** [comment] 2018-05-14 02:09
same here!

**Comment by kpvsrkp** [comment] 2018-05-15 04:08
same here. Is the fix planned down the line?

**Comment by davidpobi** [comment] 2018-05-15 16:18
same here

**Comment by safarmer** [comment] 2018-05-15 17:03
I ran into this issue today and it seemed to be related to having a logged in Firebase auth state. I pushed the same code to two different Firebase hosting projects and it worked on one and not the other. The site that worked was logged out. Once I clear cookies etc for the broken site and logged in again it started working.

**Comment by benjamincombes** [comment] 2018-05-16 08:13
Same problem for me, it throws the error for some users, and works for some other users.

**Comment by amam62** [comment] 2018-05-16 13:28
same here. works for the first time but when I close the browser and open the hosted site I get this error.

**Comment by safarmer** [comment] 2018-05-19 01:27
Is there any update from the Firebase team on this?

**Comment by toffuser** [comment] 2018-05-19 02:47
No, i posted the issue at stackoverflow and no answers from anyone.. how can we open a bug at firebase? 
https://stackoverflow.com/questions/50402963/firebase-database-exception-was-thrown-by-user-callback-typeerror-cannot-rea

**Comment by hiepxanh** [comment] 2018-05-21 15:43
same to me :(

**Comment by FatimahSanni** [comment] 2018-05-22 07:41
Same :-(

**Comment by hiepxanh** [comment] 2018-05-22 07:43
I think we should close this issue, since it not problem from angularfire, it is firebasejs sdk

**Comment by FatimahSanni** [comment] 2018-05-22 07:54
@hiepxanh, really? Found a solution?

**Comment by keith-nativemobile** [comment] 2018-05-23 23:53
Not sure how you can be sure it's not a problem with angularfire as the people reporting it all seem to be using angular - or at least I can't find others experiencing this problem.  I'm seeing the same problem as everyone else, only when compiled with --prod.

**Comment by jli-lhm** [comment] 2018-05-24 09:28
I'm getting the same exception but only when I'm trying to access my website from my workplace proxy. At home I can connect without any issues.

**Comment by toffuser** [comment] 2018-05-28 19:04
I found a workaround : https://stackoverflow.com/questions/50402963/firebase-database-exception-was-thrown-by-user-callback-typeerror-cannot-rea

But it doesn`t explain the main problem.

**Comment by Viktor19931** [comment] 2018-05-31 07:55
I am having the same issue as well! In dev the code runs fine, once I switch to ng build --prod i get the following message when i run the app Cannot read property 'myID' of undefined

**Comment by angelnikolov** [comment] 2018-05-31 09:43
Same issue here, it seems that if you delete Firebase's cookies it will work, however once those are available it just starts spitting the error. Maybe that's why many people reported it as an issue which is not always easily reproducible.

**Comment by arunrajahgopal** [comment] 2018-05-31 10:17
@angelnikolov, That is true. The issue is affecting only the system of the developers (presumably) who have ping the application from a dev environment (thereby creating the login cookie) and then try to access them from a prod env. To avoid this issue, one can clear the cookies and hitting the prod env. Or just give it to your tester or manager who aren't using the dev env. It will work for them. Either ways, this is still and issue and needs attention from the angularfirebase, Not a P1 though.

**Comment by mubashshirul** [comment] 2018-06-01 07:09
I have solved this issue. Just do this in your app.component.ts
```
constructor() {
    localStorage.removeItem('firebase:previous_websocket_failure');
}
```

**Comment by Dupflo** [comment] 2018-06-01 10:58
@mubashshirul 

You just save me ! I'm using React and it solved this error ! 

Thank you very much

**Comment by GeorgiyZhuravlev** [comment] 2018-06-04 08:11
Ths same problem with already bundled (--prod) and deployed to hosting app. After weeks of work has eventually crashed with this error

**Comment by FatimahSanni** [comment] 2018-06-12 14:22
@mubashshirul Thank you! Worked like a charm

**Comment by maxx-kl** [comment] 2018-07-10 13:04
@mubashshirul 's solution worked good, but error sporadically appeared not only on developer but on clients' computers too. Now after using `ng build --prod  --build-optimizer=false` everything is OK for more than a week.

**Comment by aroncal** [comment] 2019-01-25 12:01
Same here with:
```
@angular       5.2.11
angularfire2   5.0.0-rc.7
firebase       4.13.1
```
After network disconnection and later reconnection, error starts popping up, and gathered data cannot be sent to Firebase anymore.

**Comment by johnedvard** [comment] 2019-04-04 06:12
I Experienced the same problem as @aroncal . At first, I thought it was a problem related to the user login token timing out, but no, it seems to be network disconnect and reconnect related. I will try to downgrade to firebase#4.12.1 myself and see if it works

**Comment by Bktechmasala** [comment] 2019-07-10 18:56
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg

**Comment by zarko-tg** [comment] 2020-01-10 15:18
No official fix for this yet? It's still alive even on a wrong GitHub project, since the problem is apparent when using only the JS Database / library.

**Comment by kingychiu** [comment] 2020-05-04 16:48
> @mubashshirul 's solution worked good, but error sporadically appeared not only on developer but on clients' computers too. Now after using `ng build --prod --build-optimizer=false` everything is OK for more than a week.

This is working to our case. in our case removing the localstorage item didn't help. 

I changed from `ng build --prod --aot --build-optimizer` to `ng build --prod --aot --build-optimizer=false`

**Closed** 2020-05-05 11:44 UTC

**Comment by cortez87** [comment] 2021-02-22 21:19
Why this issue is closed if now on 2021 is still occurring with --prod devices?
