### ISSUE TITLE
$firebaseAuth() methods don't return a Promise object as expected

### ISSUE THREAD

**Issue by alexsales** [firebase/angularfire#815] opened 2016-07-13 18:25 UTC
### Version info

**Angular:** 1.5.x

**Firebase:** 3.0.x

**AngularFire:** 2.0.x

### Expected behavior

(Using vanilla Firebase SDK's firebase.auth()): Examples found in `docs/guide/user-auth.md#managing-users` and `docs/reference.md#createuserwithemailandpasswordemail-password` return a Promise object and the success/error callbacks are called as expected:
[https://plnkr.co/Xq8wgRk0MX43AnkuTPnv](https://plnkr.co/Xq8wgRk0MX43AnkuTPnv)

**Note:** In the examples above (using the vanilla Firebase SDK), when the values of $scope.error and $scope.message changes, the DOM bindings wouldn't immediately update. I had to wrap them in $scope.$apply() to trigger a $digest cycle so the View would update. Not sure if this should be in a separate "New Issue" or if the docs' examples should be updated? 

### Actual behavior

(Using AngularFire's $firebaseAuth()): Examples found in `docs/guide/user-auth.md#managing-users` and `docs/reference.md#createuserwithemailandpasswordemail-password` don't seem to return a Promise object and so the success/error callbacks are never called:
[https://plnkr.co/P0Cjd9NGF9vNsFUI9WSp](https://plnkr.co/P0Cjd9NGF9vNsFUI9WSp)

**Comment by leblancmeneses** [comment] 2016-07-15 03:06
Updated plunker. https://plnkr.co/edit/M6PwgBJCB7dtcXvt3MCi

Verified that angularfire does not call the error handlers then(.., xx) or catch( ) when the post fails.


If you look at the network stack you get a 400.

Your actual error is:
```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "EMAIL_EXISTS"
   }
  ],
  "code": 400,
  "message": "EMAIL_EXISTS"
 }
}
```

**Comment by jwngr** [comment] 2016-07-15 07:34
Dupe of #782. Just upgrade to the latest `2.0.1` release: https://github.com/firebase/angularfire/releases/tag/v2.0.1.

**Closed by jwngr** 2016-07-15 07:34 UTC
