### ISSUE TITLE
$createUserWithEmailAndPassword doesn't return the authData

### ISSUE THREAD

**Issue by williamdang1710** [firebase/angularfire#757] opened 2016-06-04 04:41 UTC
When I try to create a new user with email and password using this:
```
auth.$createUserWithEmailAndPassword(email, password)
    .then(function(userData) {
        console.log("User " + userData.uid + " created successfully!");
    }).then(function(authData) {
        console.log("Logged in as:", authData.uid);
    }).catch(function(error) {
        console.error("Error: ", error);
    });
```
The user is created and signed in successfully. Howerver, there is an error say that: "`authData is undefined`".

**Comment by tgensol** [comment] 2016-06-04 17:16
+1

**Comment by davideast** [comment] 2016-06-04 22:08
@williamdang1710 @tgensol 

It should return the `firebase.User` object, which is different than the old `FirebaseAuthData` object. [Check out there reference guide here](https://firebase.google.com/docs/reference/js/firebase.User). 

The issue is in your code sample you're missing a `return` in your promise chain. Try this instead:

```js
auth.$createUserWithEmailAndPassword(email, password)
    .then(function(firebaseUser) {
        console.log("User " + firebaseUser.uid + " created successfully!");
        return firebaseUser;
    }).then(function(firebaseUser) {
        console.log("Logged in as:", firebaseUser.uid);
    }).catch(function(error) {
        console.error("Error: ", error);
    });
```

The second `.then()` is unneeded, but that should work.

[The recommended practice is to use the realtime auth state method.](https://github.com/firebase/angularfire/blob/master/docs/reference.md#onauthstatechangedcallback-context)

```js
$scope.authObj.$onAuthStateChanged(function(firebaseUser) {
  if (authData) {
    console.log("Logged in as:", firebaseUser.uid);
  } else {
    console.log("Logged out");
  }
});
```

I'm closing the issue, but reply if you're still having issues.

**Closed by davideast** 2016-06-04 22:08 UTC

**Comment by jwngr** [comment] 2016-06-07 00:15
If you are using the code David provided, the second `then()` should not be `undefined`. However, I do think he meant to add in a call to actually sign the user in after creating it:

```
auth.$createUserWithEmailAndPassword(email, password)
    .then(function(firebaseUser) {
        console.log("User " + firebaseUser.uid + " created successfully!");
        return auth.$signInWithEmailAndPassword(email, password);
    }).then(function(firebaseUser) {
        console.log("Logged in as:", firebaseUser.uid);
    }).catch(function(error) {
        console.error("Error: ", error);
    });
```

If you are still having issues, please create a minimal repro showing your issue in something like JSFiddle or Plunkr.
