### ISSUE TITLE
No option to do email verification 

### ISSUE THREAD

**Issue by mallik482** [firebase/angularfire#907] opened 2017-02-04 11:11 UTC
### Version info

**Angular:** 1.5.11

**Firebase:** 3.6.8

**AngularFire:** 2.3.0

**Other (e.g. Node, browser, operating system) (if applicable):**

### Test case

No method to do email verification of user

**Comment by jwngr** [comment] 2017-02-07 01:15
Duplicate of #764.

**Closed by jwngr** 2017-02-07 01:15 UTC
