### ISSUE TITLE
$signInWithEmailAndPassword() not returning a promise 

### ISSUE THREAD

**Issue by eshell** [firebase/angularfire#790] opened 2016-06-17 03:36 UTC
$signInWithEmailAndPassword() is also not returning a promise for me... 
```
$firebaseAuth().$signInWithEmailAndPassword(email, password).then(function(user){
  console.log('logged in:', user);
}).catch(function(error){
  console.log(error);
});
```
I do get authenticated, but nothing happens in the then blocks. no errors or anything.

```
$firebaseAuth().$onAuthStateChanged(function(user) {
      if (user) {
        vm.user = user;
      } else {
        vm.user = null;
      }
    });
```
this works just fine to show logging in and out is successful.

**Comment by jwngr** [comment] 2016-06-17 04:06
Dupe of #782. Just upgrade to the latest `2.0.1` release: https://github.com/firebase/angularfire/releases/tag/v2.0.1.

**Closed by jwngr** 2016-06-17 04:06 UTC
