### ISSUE TITLE
scopeless $bindTo

### ISSUE THREAD

**Issue by Karasuni** [firebase/angularfire#802] opened 2016-06-29 13:41 UTC
I would like to be able to work scopeless with angularfire. One of the first things I tried was using ``$bindTo``.

``$bindTo`` currently requires a scope and variable name argument:
```
(app.js)
angular.module('myApp', ["firebase"]).controller('MyController', function($firebaseObject, $scope) {
    var scopeDataRef = firebase.database().ref().child("scopeData");
    $firebaseObject(scopeDataRef).$bindTo($scope, "scopeData");
});

(index.html)
<body ng-app="myApp">
    <div ng-controller="MyController as mc">
        <h2>3-way Data binding to scope</h2>
        <input type="text" ng-model="scopeData.text"/>
        <p>You said: {{scopeData.text}}</p>
    </div>
</body>
```

Instead I would prefer to work scopeless and bind the database variable to a variable in my controller:
```
(app.js)
angular.module('myApp', ["firebase"]).controller('MyController', function($firebaseObject) {
    var dataRef = firebase.database().ref().child("data");
    $firebaseObject(dataRef).$bindTo(this, "data");
});

(index.html)
<body ng-app="myApp">
    <div ng-controller="MyController as mc">
        <h2>3-way Data binding to controller</h2>
        <input type="text" ng-model="mc.data.text"/>
        <p>You said: {{mc.data.text}}</p>
    </div>
</body>
```

Perhaps with an improved syntax.

**Comment by jwngr** [comment] 2016-06-29 16:00
Dupe of #441 and #776.

**Closed by jwngr** 2016-06-29 16:00 UTC
Labels: duplicate
