### ISSUE TITLE
feature request: $firebaseArray $add/$remove update local copy immediately

### ISSUE THREAD

**Issue by charlierudolph** [firebase/angularfire#829] opened 2016-07-28 16:59 UTC
I would like $firebaseArray.$add and $remove to update the local copy immediately instead of waiting until it has been synced with the database. This way my user interface can make use of the updated array and sync the database in the background.

**Comment by davideast** [comment] 2016-07-28 22:34
@charlierudolph That is exactly what happens. Under the hood the SDK updates a local cache and sends the write off to the database. If the write is rejected it is rolled back locally.

**Comment by charlierudolph** [comment] 2016-07-28 22:52
That was not what I saw. After the call to `$remove`, the array has not been updated. Looking at the code, I only see the call directly to firebase. The local cache doesn't appear to be updated until the `child_removed` event is fired.

**Comment by jaymanned** [comment] 2016-07-31 18:46
Same issue here. After $remove() the local array keeps the deleted record until updated at server. Just found out and having huge problems sync problems with my app.

**Comment by jaymanned** [comment] 2016-07-31 19:03
FYI I'm on angularfire 1.2.0.

**Comment by charlierudolph** [comment] 2016-08-01 18:31
I'm on angular fire 2.0.1

**Comment by jwngr** [comment] 2016-08-16 21:08
There do seem to be some bugs around how and when we raise local events. For example, in `$firebaseArray.add()`, we don't [raise the `child_added` notification](https://github.com/firebase/angularfire/blob/master/src/database/FirebaseArray.js#L125) until after we [hear back from the server that the write was successful](https://github.com/firebase/angularfire/blob/master/src/database/FirebaseArray.js#L124). This probably leads to some weird behavior with regards to latency compensation, especially in offline situations.

**Comment by katowulf** [comment] 2016-08-16 23:32
@jwngr that only affects the $watch() listeners. Latency compensation should be getting applied and the local child_added and child_removed events should be immediate. 

Since we're writing/removing directly at the SDK, I can't really tell how this is an AngularFire bug yet. It's possible that we're not notifying the compiler correctly for locally added/removed events, but I don't see anything obvious in the code.

I'd really like to see a minimal repro if anyone is willing to produce one.

As for the $watch behavior, I looked this over and at first I wasn't sure why that `$$notify` is necessary inside of `$add` at all. Presumably, this should be handled in `$$process` normally, like any other `child_added` event (and it would be triggered closer to the time the array is modified). 

But for some non-obvious reason, `$$process` doesn't trigger the child_added notification for locally added events. So [some unknown body](https://github.com/katowulf) ["fixed" this](https://github.com/firebase/angularfire/commit/b8ac87a136dceefbea011f5ff4b9183e44e3cc45) by the best means possible, at some time long ago. : (

**Comment by jwngr** [comment] 2016-08-17 00:01
> that only affects the `$watch()` listeners

I guess I assumed that was the whole crux of the issue. If `$watch()` isn't being called, I assumed the digest loop isn't running, then the view will not get updated at all, even though the local cache will be updated by the underlying Firebase SDK.

That being said, I just put together [a Plunker testing `$add()`](https://plnkr.co/edit/nlemqy) and am not able to reproduce the issue. If you turn of your wifi (to simulate not being able to hit the Realtime Database) and click the button, data is updated locally. And when you turn wifi back on, the data syncs with Firebase.

@charlierudolph / @jaymanned - Is my Plunkr now simulating your situation properly? Can you see if you can get a live repro for us to debug?

**Comment by katowulf** [comment] 2016-08-17 00:19
Yeah, $watch() is independent of the handling, which is all done in $$added and $$process. The fact that the $$notify is there at all is a bit of a hack. For background, it's pretty difficult to solve this perfectly, because it's unclear what to do if the record already exists in the array (do you trigger the notify anyway? do you consider it a known record?). 

Putting the notify in the $add method (which was $save at the time of the change, I think) seemed best at the time to avoid these nuances, but I clearly missed the fact that it's not triggered in tandem with the actual add event.

**Comment by jaymanned** [comment] 2016-08-17 08:51
> Since we're writing/removing directly at the SDK, I can't really tell how this is an AngularFire bug yet. It's possible that we're not notifying the compiler correctly for locally added/removed events, but I don't see anything obvious in the code.

I mainly use AngularFire and very little Firebase js client. If the issue is at the Firebase client, maybe that behaviour propagates into the $firebaseArray.$add/$remove which is where I see it.

**Comment by katowulf** [comment] 2016-08-30 14:38
Closing this until we see a minimal repro as, by design, Firebase's latency compensation would provide this as described and it should be WAI. If there is a bug, we'd love to see it.

**Closed by katowulf** 2016-08-30 14:38 UTC
Labels: bug

**Comment by jaymanned** [comment] 2016-09-03 07:53
Hi all. [Here is the bug repro](http://jsfiddle.net/jaymann/42pyoytf/4/). Sorry I couldn't come back before. As you can see once you `$remove` an item in the `$firebaseArray` it is still there until the record is deleted at the server and the related event is received.

**Comment by jwngr** [comment] 2016-09-05 22:17
Thanks for the repro. I took a look and I think you are misunderstanding JavaScript asynchronous behavior as a bug in AngularFire. There are a few things wrong with the repro:
 1. It uses Firebase `2.2.4` and AngularFire `1.2.0`, both of which are nearly half a year old and have been heavily changed with the release of Firebase `3.x.x` and AngularFire `2.x.x`.
 2. The repro does not properly wait for all three initial `$add()` promises to complete before running more code. It only waits for the last one. This should be fine in most cases, but can lead to some nasty race conditions.
 3. The call to `$remove()` is asynchronous while the change of the display text is synchronous. This again leads to a race condition, even before the network request is made.

Neither Kato nor I have been able to see an issue with how things currently work. My [Plunker repro](https://plnkr.co/edit/nlemqy) from https://github.com/firebase/angularfire/issues/829#issuecomment-240276159 shows pretty clearly that latency compensation is working correctly. As such, I do not think there is a bug here.

**Comment by jaymanned** [comment] 2016-09-06 06:43
Hi Jacob

I'm sorry to disagree. Those things you mention do not explain at all what's happening. I could change the jsfiddle but we both know it would not go away. The fact is that the API states that local objects should be updated immediately, regardless of the version, regardless of  latency compensation. Expected behavior is not met, so by definition this is canonically a bug. 

Actually, It's kind of troubling having to have this discuss. If you guys just don't want to tackle this please let me know. I'll introduce workarounds to compensate this _no-bug_ in our code. But at this stage we cannot move to Firebase 3 without heavy rework.

**Comment by jwngr** [comment] 2016-09-06 16:31
No worries on disagreeing. I'm not trying to be difficult or disregard your request for help here. I'm sorry if I came across that way. Kato and I both care a lot about making sure this library is as useful and bug-free as possible. We don't just close issues because we don't want to fix things. We close them when there's no clear actionable issue.

In my honest opinion, the JSFiddle you shared contains some non-standard programming practices when dealing with asynchronous code. I do not think it is a real use case and I see at least two places in it with race conditions (as mentioned in my previous comment). I would consider these bugs in the repro, not in the underlying AngularFire library. I think [my Plunker](https://plnkr.co/edit/nlemqy) is a better test of the behavior we are testing. Have you taken a look at it and tried testing it with your wifi on and then with your wifi off as I described in https://github.com/firebase/angularfire/issues/829#issuecomment-240276159? Does it not prove to you that AngularFire is updating the local data even though we never contact the server? If not, what exactly would you expect to happen in this case?

**Comment by jaymanned** [comment] 2016-09-07 20:16
HI Jacob

I've updated the [jsfiddle](http://jsfiddle.net/jaymann/42pyoytf/6/) to remove that unlikely race condition you mentioned. Guess what, the bug is still there. The other race condition you referred to is simply not so as I'm using $remove's return promise to run the display updating code in what anyone would agree is standard angular/async programming practice.

I'm mean no disrespect but please do not point me again to that plunker of yours. I'm pretty sure you can come up with hundreds of examples of properly behaving code. And I truly believe that when you guys release code is because you are convinced it is sound. 

However, the fact is that in this particular piece of code, there is a bug. Moreover I've found a few instances of this bug in our code. And there is also there is a few other people in this thread that have experienced the same issue. 

I'm not going to insist anymore. But people that will land on this issue will probably end up as amazed as I am with this denial approach to bug solving.

**Comment by katowulf** [comment] 2016-09-07 20:31
Hi Javier, thanks for your persistence and your patience here. Much appreciated. It's unfortunate that the burden of proof falls back onto you, but we can't scale 1:1 support infinitely, so we need to focus on confirmed bugs that don't appear to be WAI.

Thus, without a sound, verifiable repro, this isn't going to be worth the cost to investigate. A sound, verifiable repro will meet the following conditions and this definition won't be debated further:

- Uses the recommended versions of Angular, AngularFire, and Firebase
- Does not contain any potential race conditions (whether or not we imagined them)
- Supports a real-world use case
- Follows best practices as outlined in our docs

☼, Kato
