### ISSUE TITLE
$unauth causing binding issues

### ISSUE THREAD

**Issue by douwevdijk** [firebase/angularfire#582] opened 2015-03-10 19:09 UTC
Hi All,

Not sure if I am looking in the right direction, but I am experiencing a strange issue. It looks like calling $unauth() and then logging in again with a different user is causing issues on my references and thus bindings. In other words, it looks the reference ( or binding ) remains even though the path has changed and therefore updates are made on the new and previous index.

FYI, I am using Angularfire 0.9.1 and Firebase 2.0.5 

Many thanks.

**Comment by jwngr** [comment] 2015-03-10 19:32
Duplicate of #581.

**Closed by jwngr** 2015-03-10 19:32 UTC
