### ISSUE TITLE
AngularFire $watch callback function get executed as many time is the length of Array

### ISSUE THREAD

**Issue by romelgomez** [firebase/angularfire#635] opened 2015-07-07 04:44 UTC
At the moment, i get the data the callback is executed as many time is the length of Array.

Is this the expected behavior?

Here is the example code:  http://plnkr.co/edit/PysjFG?p=info

https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-firebasearray-watchcb-context

![screenshot from 2015-07-07 00 09 17](https://cloud.githubusercontent.com/assets/2358251/8538851/0429090e-243d-11e5-8c23-52eeb20089d0.png)

Best regards.

**Comment by katowulf** [comment] 2015-07-07 08:53
That is the purpose of this function; it notifies you whenever any record changes. Are you trying to solve a specific use case?

**Comment by romelgomez** [comment] 2015-07-07 15:27
I'm making another JqTree example, this time with AngularJS and FireBase.   

https://github.com/romelgomez/jqtree-angularjs-firebase-example

To me, It seems to be, $watch callback it have a random behavior. 

In this $watch callback, i have [replaceWholeTree()](https://github.com/romelgomez/jqtree-angularjs-firebase-example/blob/master/app/scripts/categories.js#L227) function, this function is It executed as many time is the length of Array only at the beginning of the data load, and one time only when i saving a new category o node. Another random behavior happen when change two nodes or the order of the one category (moving category-A below category-B), replaceWholeTree() function is executed two times, and i think it is maybe ok, because only two records are changed at the same time, but when, i change to another part of the web site, /home for example, and then again go to /categories, and i change two records, replaceWholeTree() function is executed four times. 

This $watch callback, should be executed as many node are changed at the same time?  
In that the beginning, the nodes array as a length of zero, after the data come, $watch callback should be executed many time is it the length of Array that come?   

![screenshot from 2015-07-07 10 38 58](https://cloud.githubusercontent.com/assets/2358251/8549776/68f000fa-2496-11e5-9640-8a36df8f4664.png)


Best regards.

**Comment by jwngr** [comment] 2015-07-08 07:00
As Kato mentioned, `$watch()` is called every time a record changes (added, removed, moved, or changed). This is intended behavior. I'm not sure `replaceWholeTree()` is the proper use case for `$watch()`. If you can explain your use case instead of your solution, we can probably offer a way forward. I'm going to close this issue for now though.

**Closed by jwngr** 2015-07-08 07:00 UTC
